CREATE TABLE [dbo].[Drinks]
(
	[Number] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Gin] BIT NULL DEFAULT 0, 
    [Vodka] BIT NULL DEFAULT 0,
    [Rom] BIT NULL DEFAULT 0, 
    [Jager] BIT DEFAULT 0,
    [Cola] BIT NULL DEFAULT 0,
    [Pris] SMALLMONEY NULL
)
